import nodemailer from "nodemailer";
import config from "../config/config.js";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    type: "OAuth2",
    user: config.GOOGLE_USER,
    clientId: config.GOOGLE_CLIENT_ID,
    clientSecret: config.GOOGLE_CLIENT_SECRET,
    refreshToken: config.GOOGLE_REFRESH_TOKEN,
    // optional but recommended
    // accessToken will be auto-generated by nodemailer
  },
});

// Verify connection (safe version)
transporter.verify((error, success) => {
  if (error) {
    console.error("Error connecting to email server:", error);
  } else {
    console.log("Email server is ready to send messages");
  }
});

export const sendEmail = async (to, subject, text, html) => {
  try {
    const info = await transporter.sendMail({
      from: `"Your Name" <${config.GOOGLE_USER}>`,
      to,
      subject,
      text,
      html,
    });

    console.log("Message sent:", info.messageId);
  } catch (error) {
    console.error("Error sending email:", error);
  }
};







// import nodemailer from 'nodemailer';
// import config from '../config/config.js';


// const transporter = nodemailer.createTransport({
//     service: 'gmail',
//     auth: {
//         type: 'OAuth2',
//         user: config.GOOGLE_USER,
//         clientId: config.GOOGLE_CLIENT_ID,
//         clientSecret: config.GOOGLE_CLIENT_SECRET,
//         refreshToken: config.GOOGLE_REFRESH_TOKEN
//     }
// })


// // Verify the connection configuration
// transporter.verify((error, success) => {
//     if (error) {
//         console.error('Error connecting to email server:', error);
//     } else {
//         console.log('Email server is ready to send messages');
//     }
// });

// export const sendEmail = async (to, subject, text, html) => {
//     try {
//         const info = await transporter.sendMail({
//             from: `"Your Name" <${config.GOOGLE_USER}>`, // sender address
//             to, // list of receivers
//             subject, // Subject line
//             text, // plain text body
//             html, // html body
//         });

//         console.log('Message sent: %s', info.messageId);
//         console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
//     } catch (error) {
//         console.error('Error sending email:', error);
//     }
// };



// import nodemailer from "nodemailer";
// import { google } from "googleapis";
// import config from "../config/config.js";

// // Create OAuth2 client
// const oAuth2Client = new google.auth.OAuth2(
//   config.GOOGLE_CLIENT_ID,
//   config.GOOGLE_CLIENT_SECRET,
//   "https://developers.google.com/oauthplayground"
// );

// // Set refresh token
// oAuth2Client.setCredentials({
//   refresh_token: config.GOOGLE_REFRESH_TOKEN,
// });

// // Create transporter (async because accessToken needed)
// const createTransporter = async () => {
//   try {
//     const accessToken = await oAuth2Client.getAccessToken();

//     const transporter = nodemailer.createTransport({
//       service: "gmail",
//       auth: {
//         type: "OAuth2",
//         user: config.GOOGLE_USER,
//         clientId: config.GOOGLE_CLIENT_ID,
//         clientSecret: config.GOOGLE_CLIENT_SECRET,
//         refreshToken: config.GOOGLE_REFRESH_TOKEN,
//         accessToken: accessToken.token, // ✅ FIXED
//       },
//     });

//     return transporter;
//   } catch (error) {
//     console.error("Error creating transporter:", error);
//   }
// };

// // Verify connection
// const verifyConnection = async () => {
//   try {
//     const transporter = await createTransporter();
//     await transporter.verify();
//     console.log("Email server is ready to send messages");
//   } catch (error) {
//     console.error("Error connecting to email server:", error);
//   }
// };

// verifyConnection();

// // Send email function
// export const sendEmail = async (to, subject, text, html) => {
//   try {
//     const transporter = await createTransporter();

//     const info = await transporter.sendMail({
//       from: `"Your Name" <${config.GOOGLE_USER}>`,
//       to,
//       subject,
//       text,
//       html,
//     });

//     console.log("Message sent:", info.messageId);
//   } catch (error) {
//     console.error("Error sending email:", error);
//   }
// };







// // import nodemailer from 'nodemailer';
// // import config from '../config/config.js';


// // const transporter = nodemailer.createTransport({
// //     service: 'gmail',
// //     auth: {
// //         type: 'OAuth2',
// //         user: config.GOOGLE_USER,
// //         clientId: config.GOOGLE_CLIENT_ID,
// //         clientSecret: config.GOOGLE_CLIENT_SECRET,
// //         refreshToken: config.GOOGLE_REFRESH_TOKEN
// //     }
// // })


// // // Verify the connection configuration
// // transporter.verify((error, success) => {
// //     if (error) {
// //         console.error('Error connecting to email server:', error);
// //     } else {
// //         console.log('Email server is ready to send messages');
// //     }
// // });

// // export const sendEmail = async (to, subject, text, html) => {
// //     try {
// //         const info = await transporter.sendMail({
// //             from: `"Your Name" <${config.GOOGLE_USER}>`, // sender address
// //             to, // list of receivers
// //             subject, // Subject line
// //             text, // plain text body
// //             html, // html body
// //         });

// //         console.log('Message sent: %s', info.messageId);
// //         console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
// //     } catch (error) {
// //         console.error('Error sending email:', error);
// //     }
// // };
